### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'integratePrettier')

### ISSUE THREAD

**Issue by sygint** [danilovilhena/kickstart#24]
![Screenshot_2024-01-14_13-09-27](https://github.com/danilovilhena/kickstart-it/assets/872633/d3cf9c7e-d071-43e4-9616-e576358212bc)

**Comment by danilovilhena** [comment]
Fixed in v1.3.1 - https://github.com/danilovilhena/kickstart-it/pull/27
